using System.Collections.Generic;

namespace DMData.Names
{
    internal static partial class DataNames
    {
        static IReadOnlyList<string> ArabicFemaleNames => new List<string>() 
        {
            "Abeer",
            "Abiha",
            "Afaf",
            "Afreen",
            "Aliya",
            "Arwa",
            "Ashfa",
            "Ashraqat",
            "Atikah",
            "Boutheina",
            "Bushra",
            "Chaima",
            "Cynthia",
            "Danielle",
            "Dareen",
            "Dina",
            "Eliana",
            "Esma",
            "Feyrouz",
            "Fouz",
            "Habiba",
            "Hafsa",
            "Hajra",
            "Halima",
            "Hamida",
            "Hanifa",
            "Havva",
            "Hayat",
            "Ibtisam",
            "Inaam",
            "Jamila",
            "Jawahir",
            "Joelle",
            "Joud",
            "Jouri",
            "Julia",
            "Jumana",
            "Kareena",
            "Karima",
            "Katya",
            "Khairunnisa",
            "Khawlah",
            "Latifa",
            "Layan",
            "Lina",
            "Lulwa",
            "Madiha",
            "Mahmuna",
            "Maysoon",
            "Melissa",
            "Munira",
            "Nadia",
            "Nafisa",
            "Naima",
            "Najat",
            "Najma",
            "Nalini",
            "Nasim",
            "Nasrin",
            "Natasha",
            "Nathalie",
            "Nawal",
            "Nayla",
            "Naziha",
            "Nazira",
            "Nehal",
            "Nejla",
            "Nermin",
            "Qamar ud-Din",
            "Qistina",
            "Rabia",
            "Rahima",
            "Rania",
            "Rashida",
            "Riffat",
            "Rimas",
            "Ruqayya",
            "Sabiha",
            "Safaa",
            "Safiya",
            "Saira",
            "Sajida",
            "Sakina",
            "Salma",
            "Samira",
            "Samiya",
            "Sania",
            "Shahd",
            "Shams",
            "Shatha",
            "Shumaila",
            "Sonia",
            "Tahira",
            "Taslima",
            "Yamina",
            "Zakiya",
            "Zalayha",
            "Zoraida",
            "Zuhal",
        };
        static IReadOnlyList<string> ArabicMaleNames => new List<string>() 
        {
            "Ab",
            "Abbad",
            "Abd al-Aziz",
            "Abd al-Rahman",
            "Abd al-Uzza",
            "Abd Rabbo",
            "Abdel Fattah",
            "Abdel Nour",
            "Abdi",
            "Abdolreza",
            "Abdu",
            "Abdul Ahad",
            "Abdul Ali",
            "Abdul Alim",
            "Abdul Azim",
            "Abdul Baqi",
            "Abdul Bari",
            "Abdul Basir",
            "Abdul Basit",
            "Abdul Ghaffar",
            "Abdul Ghani",
            "Abdul Hadi",
            "Abdul Hafiz",
            "Abdul Hai",
            "Abdul Hakim",
            "Abdul Halim",
            "Abdul Hamid",
            "Abdul Haq",
            "Abdul Hussein",
            "Abdul Jabbar",
            "Abdul Jalil",
            "Abdul Jamil",
            "Abdul Karim",
            "Abdul Khaliq",
            "Abdul Latif",
            "Abdul Majid",
            "Abdul Malik",
            "Abdul Mannan",
            "Abdul Monem",
            "Abdul Qadir",
            "Abdul Qayyum",
            "Abdul Quddus",
            "Abdul Samad",
            "Abdul Sattar",
            "Abdul Wadud",
            "Abdul Wahhab",
            "Abdul Wahid",
            "Abdul Zahir",
            "Abdul Zahra",
            "Abdul",
            "Abdur Rab",
            "Abdur Rahim",
            "Abdur Raqib",
            "Abdur Rauf",
            "Abdur Razzaq",
            "Abdus Sabur",
            "Abdus Shakur",
            "Abid",
            "Abidin",
            "Abu Abdullah",
            "Abu al-Qasim",
            "Abu Hafs",
            "Abu Hamza",
            "Abu Nasir",
            "Abu'l-Fadl",
            "Adeel",
            "Adeem",
            "Adem",
            "Adham",
            "Adib",
            "Adil",
            "Adir",
            "Ahad",
            "Ahmad",
            "Ahmed Tijani",
            "Ahsan",
            "Akeem",
            "Akif",
            "Akram",
            "Alaa",
            "Ali Naqi",
            "Ali Reza",
            "Alim",
            "Aman Ali",
            "Aman",
            "Amanullah",
            "Amin al-Din",
            "Aminullah",
            "Amjad",
            "Anis",
            "Anisur Rahman",
            "Anjem",
            "Anwar",
            "Anwaruddin",
            "Aqeel",
            "Asad",
            "Asadullah",
            "Asem",
            "Asghar",
            "Asif",
            "Asil",
            "Aslam",
            "Ataullah",
            "Atif",
            "Atiq",
            "Atiqullah",
            "Awad",
            "Ayad",
            "Ayman",
            "Ayub",
            "Azem",
            "Azim",
            "Azimullah",
            "Aziz",
            "Azizullah",
            "Azizur Rahman",
            "Azmi",
            "Azus",
            "Badi",
            "Badr al-Din",
            "Bagher",
            "Baha' al-Din",
            "Baha",
            "Bahri",
            "Baki",
            "Bakir",
            "Barkat Ali",
            "Barkatullah",
            "Bashar",
            "Bashir",
            "Basri",
            "Bilel",
            "Billah",
            "Boualem",
            "Boulos",
            "Boutros",
            "Brahim",
            "Brahma Bhanu",
            "Burhan al-Din",
            "Burhan",
            "Chadli",
            "Danyal",
            "Dastgir",
            "Dawoud",
            "Dhikrullah",
            "Ehsanullah",
            "Ekram",
            "Fadel",
            "Fadel",
            "Fahd",
            "Fahd",
            "Faheem",
            "Faheem",
            "Fahmi",
            "Fahmi",
            "Fahri",
            "Fahri",
            "Faisal",
            "Faisal",
            "Faiz",
            "Faiz",
            "Faizan",
            "Faizan",
            "Faizullah",
            "Faizullah",
            "Fakhr al-Din",
            "Fakhr al-Din",
            "Fakhraddin",
            "Fakhraddin",
            "Fakhruddin",
            "Fakhruddin",
            "Faraj",
            "Faraj",
            "Farhat",
            "Farhat",
            "Farid",
            "Farid",
            "Fariduddin",
            "Fariduddin",
            "Farooq",
            "Farooq",
            "Fasih",
            "Fasih",
            "Fathallah",
            "Fathallah",
            "Fathi",
            "Fathi",
            "Fatin",
            "Fatin",
            "Fawaz",
            "Fawaz",
            "Fawzi",
            "Fawzi",
            "Fayez",
            "Fayez",
            "Fazel",
            "Fazel",
            "Fazl ur Rahman",
            "Fazl ur Rahman",
            "Fazl",
            "Fazl",
            "Fazlallah",
            "Fazlallah",
            "Fazli",
            "Fazli",
            "Fazlul Haq",
            "Fazlul Haq",
            "Fazlul Karim",
            "Fazlul Karim",
            "Fikri",
            "Fikri",
            "Fouad",
            "Fouad",
            "Fouzan",
            "Fouzan",
            "Fuad",
            "Fuad",
            "Furkan",
            "Furkan",
            "Habib ur Rahman",
            "Habib",
            "Habibullah",
            "Hadem",
            "Hadi",
            "Hafeez",
            "Hafizullah",
            "Haitham",
            "Hajji (name)",
            "Hakam",
            "Haldun",
            "Halim",
            "Hamdan",
            "Hamdi",
            "Hamid al-Din",
            "Hamid",
            "Hamidullah",
            "Harun",
            "Hashem",
            "Hashim",
            "Hassim",
            "Hatem",
            "Hayatullah",
            "Haydar",
            "Hazem",
            "Hibat Allah",
            "Hichem",
            "Hidayatullah",
            "Hikmat",
            "Hilmi",
            "Hisham ud-Din",
            "Hossam",
            "Hurairah",
            "Husam ad-Din",
            "Hussein",
            "Ibro",
            "Idris",
            "Ihab",
            "Ikhtiyar al-Din",
            "Ikramullah",
            "Ikrimah",
            "Ilyas",
            "Imad al-Din",
            "Imad",
            "Imran",
            "Imtiaz",
            "Inaam",
            "Inam-ul-Haq",
            "Inayatullah",
            "Iqbal",
            "Ishtiaq",
            "Iskandar",
            "Ismat ad-Din",
            "Ismatullah",
            "Izz al-Din",
            "Izzatullah",
            "Jaber",
            "Jabir",
            "Jabr",
            "Ja'far",
            "Jahid",
            "Jalal ad-Din",
            "Jalal",
            "Jamal ad-Din",
            "Jamal",
            "Jameel",
            "Jamil",
            "Jasem",
            "Jawdat",
            "Jubayr",
            "Junayd",
            "Jurj",
            "Ka'b",
            "Kadeem",
            "Kadir",
            "Kafeel",
            "Kamal ad-Din",
            "Kamil",
            "Karem",
            "Karim",
            "Kashif",
            "Kazem",
            "Khadem",
            "Khair ad-Din",
            "Khakim",
            "Khakim",
            "Khalfan",
            "Khalid",
            "Khalifah",
            "Khalil-ur-Rehman",
            "Kulthum",
            "Labib",
            "Lalji",
            "Latif",
            "Luay",
            "Lutfullah",
            "Lutfur Rahman",
            "Mahalati",
            "Mahbubur",
            "Mahir",
            "Mahmud",
            "Mamdouh",
            "Mansur",
            "Manzur",
            "Marwan",
            "Masoud",
            "Maytham",
            "Mehdi",
            "Melhem",
            "Midhat",
            "Min",
            "Mizanur Rahman",
            "Moatassem",
            "Moeen",
            "Moemen",
            "Mohammad Taqi",
            "Mohannad",
            "Mohy al-Din",
            "Moinuddin",
            "Mojtaba",
            "Moncef",
            "Moneim",
            "Mua'dh",
            "Muammer",
            "Muharrem",
            "Muhibullah",
            "Muhsin",
            "Mu'iz ad-Din",
            "Mukhtar",
            "Mumtaz",
            "Munib",
            "Munif",
            "Munir",
            "Murad",
            "Murtaza",
            "Mustafa",
            "Muzaffar",
            "Nabih",
            "Nabil",
            "Nadeem",
            "Nader",
            "Naguib",
            "Nahyan",
            "Naim",
            "Naji",
            "Najib",
            "Najibullah",
            "Najm al-Din",
            "Najm",
            "Naqibullah",
            "Naseeb",
            "Naseer",
            "Nasim",
            "Nasir al-Din",
            "Nasir",
            "Nasrallah",
            "Nasri",
            "Nassif",
            "Nasuh",
            "Nawaf",
            "Nawaz",
            "Nazif",
            "Nazim",
            "Nazimuddin",
            "Nazmi",
            "Nihad",
            "Nimatullah",
            "Nizam al-Din",
            "Nowfal",
            "Nu'man",
            "Nur al-Din",
            "Nur",
            "Nurullah",
            "Nusrat",
            "Qaid",
            "Qaid",
            "Qamar ud-Din",
            "Qamar ud-Din",
            "Qasymbek",
            "Qasymbek",
            "Quddus",
            "Quddus",
            "Qudratullah",
            "Qudratullah",
            "Qusay",
            "Qusay",
            "Qutb ad-Din",
            "Qutb ad-Din",
            "Qutb",
            "Qutb",
            "Sa‘id",
            "Saad",
            "Saadallah",
            "Sabah ad-Din",
            "Sabri",
            "Sa'd al-Din",
            "Sadik",
            "Sadr al-Din",
            "Safi al-Din",
            "Safiullah",
            "Sahir",
            "Saifullah",
            "Saifur Rahman",
            "Sajid",
            "Sajjad",
            "Salim",
            "Samadu",
            "Samee",
            "Samir",
            "Samirah",
            "Samiullah",
            "Sanaullah",
            "Saqib",
            "Sarmad",
            "Satam",
            "Sattar",
            "Saud",
            "Sayeeda",
            "Sayf al-Din",
            "Seif ilislam",
            "Shafiq ur Rahman",
            "Shafiqullah",
            "Shaheed",
            "Shakir",
            "Shams al-Din",
            "Shams",
            "Shamsur Rahman",
            "Sharaf al-Din",
            "Sharifullah",
            "Shawkat",
            "Shawki",
            "Shihab al-Din",
            "Shujauddin",
            "Shukri",
            "Sidique",
            "Sidqi",
            "Sirajuddin",
            "Suhail",
            "Suleiman",
            "Tahmid",
            "Tahsin",
            "Talal",
            "Talat",
            "Taqi al-Din",
            "Taqi",
            "Tarazi",
            "Tariq",
            "Tawfik",
            "Tayeb",
            "Tayfur",
            "Tufail",
            "Ubayd Allah",
            "Uday",
            "Wadih",
            "Wadud",
            "Wael",
            "Wafi",
            "Wahed",
            "Wahid",
            "Wajdi",
            "Waleed",
            "Wasim",
            "Wazir",
            "Wissem",
            "Yacinew",
            "Yadollah",
            "Yahir",
            "Yakub",
            "Yasser",
            "Yunus",
            "Yusuf Ali",
            "Yusuf",
            "Zafarullah",
            "Zafer",
            "Zahed",
            "Zahir al-Din",
            "Zahir",
            "Zaid",
            "Zainal Abidin",
            "Zainal",
            "Zakariya",
            "Zaki",
            "Zane",
            "Zayn ad-Din",
            "Zeeshan",
            "Ziad",
            "Ziauddin",
        };
    }
}
