using System.Collections.Generic;

namespace DMData.Names
{
    static class DataMilitary
    {
        public static IReadOnlyList<MilitaryBranch> GetMilitaryBranchData()
        {
            return new List<MilitaryBranch>()
            {
                new MilitaryBranch(MilitaryCategoryType.Greek, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O10, "Strategos"),
                    new MilitaryRank(MilitaryGradeType.O7, "Polemarchos"),
                    new MilitaryRank(MilitaryGradeType.O7, "Taxiarhos"),
                    new MilitaryRank(MilitaryGradeType.O6, "Syntagmatarchis"),
                    new MilitaryRank(MilitaryGradeType.O4, "Tagmatarches"),
                    new MilitaryRank(MilitaryGradeType.O3, "Lokhagos"),
                    new MilitaryRank(MilitaryGradeType.E1, "Hoplites"),
                    new MilitaryRank(MilitaryGradeType.E5, "Hoplomachos"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Greek, MilitaryBranchType.Cavalry, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O6, "Epihipparch"),
                    new MilitaryRank(MilitaryGradeType.O4, "Hipparchos"),
                    new MilitaryRank(MilitaryGradeType.O4, "Hipparmostes"),
                    new MilitaryRank(MilitaryGradeType.O3, "Tetrarch"),
                    new MilitaryRank(MilitaryGradeType.E3, "Hippikon"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Greek, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O6, "Trierarch"),
                    new MilitaryRank(MilitaryGradeType.O10, "Nauarchos"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Roman, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O4, "Legatus"),
                    new MilitaryRank(MilitaryGradeType.O10, "Praetor"),
                    new MilitaryRank(MilitaryGradeType.O6, "Paefectus Castrorum"),
                    new MilitaryRank(MilitaryGradeType.O3, "Centurion"),
                    new MilitaryRank(MilitaryGradeType.O1, "Optio"),
                }),
                new MilitaryBranch(MilitaryCategoryType.UnitedStates, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O10, "General"),
                    new MilitaryRank(MilitaryGradeType.O9, "Lt. General"),
                    new MilitaryRank(MilitaryGradeType.O8, "Major General"),
                    new MilitaryRank(MilitaryGradeType.O7, "Brigadier General"),
                    new MilitaryRank(MilitaryGradeType.O6, "Colonel"),
                    new MilitaryRank(MilitaryGradeType.O5, "Lt. Colonel"),
                    new MilitaryRank(MilitaryGradeType.O4, "Major"),
                    new MilitaryRank(MilitaryGradeType.O3, "Captain"),
                    new MilitaryRank(MilitaryGradeType.O2, "1st Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.O1, "2nd Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.W5, "Chief Warrant Officer, Five"),
                    new MilitaryRank(MilitaryGradeType.W4, "Chief Warrant Officer, Four"),
                    new MilitaryRank(MilitaryGradeType.W3, "Chief Warrant Officer, Three"),
                    new MilitaryRank(MilitaryGradeType.W2, "Chief Warrant Officer, Two"),
                    new MilitaryRank(MilitaryGradeType.W1, "Warrant Officer, One"),
                    new MilitaryRank(MilitaryGradeType.E9, "Command Sergeant Major"),
                    new MilitaryRank(MilitaryGradeType.E9, "Sergeant Major"),
                    new MilitaryRank(MilitaryGradeType.E8, "First Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E8, "Master Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E7, "Sergeant First Class"),
                    new MilitaryRank(MilitaryGradeType.E6, "Staff Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E5, "Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E4, "Specialist/Corporal"),
                    new MilitaryRank(MilitaryGradeType.E3, "Private First Class"),
                    new MilitaryRank(MilitaryGradeType.E2, "Private"),
                    new MilitaryRank(MilitaryGradeType.E1, "Private"),
                }),
                new MilitaryBranch(MilitaryCategoryType.UnitedStates, MilitaryBranchType.Marines, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O10, "General"),
                    new MilitaryRank(MilitaryGradeType.O9, "Lt. General"),
                    new MilitaryRank(MilitaryGradeType.O8, "Major General"),
                    new MilitaryRank(MilitaryGradeType.O7, "Brigadier General"),
                    new MilitaryRank(MilitaryGradeType.O6, "Colonel"),
                    new MilitaryRank(MilitaryGradeType.O5, "Lt. Colonel"),
                    new MilitaryRank(MilitaryGradeType.O4, "Major"),
                    new MilitaryRank(MilitaryGradeType.O3, "Captain"),
                    new MilitaryRank(MilitaryGradeType.O2, "1st Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.O1, "2nd Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.W5, "Chief Warrant Officer, Five"),
                    new MilitaryRank(MilitaryGradeType.W4, "Chief Warrant Officer, Four"),
                    new MilitaryRank(MilitaryGradeType.W3, "Chief Warrant Officer, Three"),
                    new MilitaryRank(MilitaryGradeType.W2, "Chief Warrant Officer, Two"),
                    new MilitaryRank(MilitaryGradeType.W1, "Warrant Officer, One"),
                    new MilitaryRank(MilitaryGradeType.E9, "Sergeant Major"),
                    new MilitaryRank(MilitaryGradeType.E9, "Master Gunnery Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E8, "First Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E8, "Master Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E7, "Gunnery Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E6, "Staff Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E5, "Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E4, "Corporal"),
                    new MilitaryRank(MilitaryGradeType.E3, "Lance Corporal"),
                    new MilitaryRank(MilitaryGradeType.E2, "Private First Class"),
                    new MilitaryRank(MilitaryGradeType.E1, "Private"),
                }),
                new MilitaryBranch(MilitaryCategoryType.UnitedStates, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O10, "Admiral"),
                    new MilitaryRank(MilitaryGradeType.O9, "Vice Admiral"),
                    new MilitaryRank(MilitaryGradeType.O8, "Rear Admiral (upper half)"),
                    new MilitaryRank(MilitaryGradeType.O7, "Rear Admiral (lower half)"),
                    new MilitaryRank(MilitaryGradeType.O6, "Captain"),
                    new MilitaryRank(MilitaryGradeType.O5, "Commander"),
                    new MilitaryRank(MilitaryGradeType.O4, "Lt. Commander"),
                    new MilitaryRank(MilitaryGradeType.O3, "Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.O2, "Lieutenant, JG"),
                    new MilitaryRank(MilitaryGradeType.O1, "Ensign"),
                    new MilitaryRank(MilitaryGradeType.W5, "Chief Warrant Officer, Five"),
                    new MilitaryRank(MilitaryGradeType.W4, "Chief Warrant Officer, Four"),
                    new MilitaryRank(MilitaryGradeType.W3, "Chief Warrant Officer, Three"),
                    new MilitaryRank(MilitaryGradeType.W2, "Chief Warrant Officer, Two"),
                    new MilitaryRank(MilitaryGradeType.W1, "Warrant Officer, One"),
                    new MilitaryRank(MilitaryGradeType.E9, "Command Master Chief Petty Officer"),
                    new MilitaryRank(MilitaryGradeType.E9, "Master Chief Petty Officer"),
                    new MilitaryRank(MilitaryGradeType.E8, "Command Senior Chief Petty Officer"),
                    new MilitaryRank(MilitaryGradeType.E8, "Senior Chief Petty Officer"),
                    new MilitaryRank(MilitaryGradeType.E7, "Chief Petty Officer"),
                    new MilitaryRank(MilitaryGradeType.E6, "Petty Officer First Class"),
                    new MilitaryRank(MilitaryGradeType.E5, "Petty Officer Second Class"),
                    new MilitaryRank(MilitaryGradeType.E4, "Petty Officer Third Class"),
                    new MilitaryRank(MilitaryGradeType.E3, "Seaman"),
                    new MilitaryRank(MilitaryGradeType.E2, "Seaman Apprentice"),
                    new MilitaryRank(MilitaryGradeType.E1, "Seaman Recruit"),
                }),
                new MilitaryBranch(MilitaryCategoryType.UnitedStates, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O10, "General"),
                    new MilitaryRank(MilitaryGradeType.O9, "Lt. General"),
                    new MilitaryRank(MilitaryGradeType.O8, "Major General"),
                    new MilitaryRank(MilitaryGradeType.O7, "Brigadier General"),
                    new MilitaryRank(MilitaryGradeType.O6, "Colonel"),
                    new MilitaryRank(MilitaryGradeType.O5, "Lt. Colonel"),
                    new MilitaryRank(MilitaryGradeType.O4, "Major"),
                    new MilitaryRank(MilitaryGradeType.O3, "Captain"),
                    new MilitaryRank(MilitaryGradeType.O2, "1st Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.O1, "2nd Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.E9, "Command Chief Master Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E9, "Chief Master Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E8, "Senior Master Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E7, "Master Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E6, "Technical Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E5, "Staff Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E4, "Senior Airman"),
                    new MilitaryRank(MilitaryGradeType.E3, "Airman First Class"),
                    new MilitaryRank(MilitaryGradeType.E2, "Airman"),
                    new MilitaryRank(MilitaryGradeType.E1, "Airman Basic"),
                }),
                new MilitaryBranch(MilitaryCategoryType.China, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O1, "Shao wei"),
                    new MilitaryRank(MilitaryGradeType.O1, "Zhong wei"),
                    new MilitaryRank(MilitaryGradeType.O2, "Shang wei"),
                    new MilitaryRank(MilitaryGradeType.O3, "Shao xiao"),
                    new MilitaryRank(MilitaryGradeType.O4, "Zhong xiao"),
                    new MilitaryRank(MilitaryGradeType.O5, "Shang xiao"),
                    new MilitaryRank(MilitaryGradeType.O6, "Da xiao"),
                    new MilitaryRank(MilitaryGradeType.O7, "Shao jiang"),
                    new MilitaryRank(MilitaryGradeType.O8, "Zhong jiang"),
                    new MilitaryRank(MilitaryGradeType.O9, "Shang jiang"),
                    new MilitaryRank(MilitaryGradeType.E1, "Lie bing"),
                    new MilitaryRank(MilitaryGradeType.E2, "Shang deng bing"),
                    new MilitaryRank(MilitaryGradeType.E3, "Xia shi"),
                    new MilitaryRank(MilitaryGradeType.E4, "Zhong shi"),
                    new MilitaryRank(MilitaryGradeType.E5, "Shang shi"),
                    new MilitaryRank(MilitaryGradeType.E6, "Si ji jun shi zhang"),
                    new MilitaryRank(MilitaryGradeType.E7, "San ji jun shi zhang"),
                    new MilitaryRank(MilitaryGradeType.E8, "Er ji jun shi zhang"),
                    new MilitaryRank(MilitaryGradeType.E9, "Yi ji jun shi zhang"),
                }),
                new MilitaryBranch(MilitaryCategoryType.China, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O1, "Hai Jun Shao Wei"),
                    new MilitaryRank(MilitaryGradeType.O1, "Hai Jun Zhong Wei"),
                    new MilitaryRank(MilitaryGradeType.O2, "Hai Jun Shang Wei"),
                    new MilitaryRank(MilitaryGradeType.O3, "Hai Jun Shao Xiao"),
                    new MilitaryRank(MilitaryGradeType.O4, "Hai Jun Zhong Xiao"),
                    new MilitaryRank(MilitaryGradeType.O5, "Hai Jun Shang Xiao"),
                    new MilitaryRank(MilitaryGradeType.O6, "Hai Jun Da Xiao"),
                    new MilitaryRank(MilitaryGradeType.O7, "Hai Jun Shao Jiang"),
                    new MilitaryRank(MilitaryGradeType.O8, "Hai Jun Zhong Jiang"),
                    new MilitaryRank(MilitaryGradeType.O9, "Hai Jun Shang Jiang"),
                    new MilitaryRank(MilitaryGradeType.E1, "Hai Jun Lie Bing"),
                    new MilitaryRank(MilitaryGradeType.E2, "Hai Jun Shang Deng Bing"),
                    new MilitaryRank(MilitaryGradeType.E3, "Hai Jun Xia Shi"),
                    new MilitaryRank(MilitaryGradeType.E4, "Hai Jun Zhong Shi"),
                    new MilitaryRank(MilitaryGradeType.E5, "Hai Jun Shang Shi"),
                    new MilitaryRank(MilitaryGradeType.E6, "Hai Jun Da Shi"),
                    new MilitaryRank(MilitaryGradeType.E7, "Hai Jun San Ji Jun Shi Zhang"),
                    new MilitaryRank(MilitaryGradeType.E8, "Hai Jun Er Ji Jun Shi Zhang"),
                    new MilitaryRank(MilitaryGradeType.E9, "Hai Jun Yi Ji Jun Shi Zhang"),
                }),
                new MilitaryBranch(MilitaryCategoryType.China, MilitaryBranchType.Airforce, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O1, "Kong Jun Shao Wei"),
                    new MilitaryRank(MilitaryGradeType.O1, "Kong Jun Zhong Wei"),
                    new MilitaryRank(MilitaryGradeType.O2, "Kong Jun Shang Wei"),
                    new MilitaryRank(MilitaryGradeType.O3, "Kong Jun Shao Xiao"),
                    new MilitaryRank(MilitaryGradeType.O4, "Kong Jun Zhong Xiao"),
                    new MilitaryRank(MilitaryGradeType.O5, "Kong Jun Shang Xiao"),
                    new MilitaryRank(MilitaryGradeType.O6, "Kong Jun Da Xiao"),
                    new MilitaryRank(MilitaryGradeType.O7, "Kong Jun Shao Jiang"),
                    new MilitaryRank(MilitaryGradeType.O8, "Kong Jun Zhong Jiang"),
                    new MilitaryRank(MilitaryGradeType.O9, "Kong Jun Shang Jiang"),
                    new MilitaryRank(MilitaryGradeType.E1, "Kong Jun Lie Bing"),
                    new MilitaryRank(MilitaryGradeType.E2, "Kong Jun Shang Deng Bing"),
                    new MilitaryRank(MilitaryGradeType.E3, "Kong Jun Xia Shi"),
                    new MilitaryRank(MilitaryGradeType.E4, "Kong Jun Zhong Shi"),
                    new MilitaryRank(MilitaryGradeType.E5, "Kong Jun Shang Shi"),
                    new MilitaryRank(MilitaryGradeType.E6, "Kong Jun Da Shi"),
                    new MilitaryRank(MilitaryGradeType.E7, "Kong Jun San Ji Jun Shi Zhang"),
                    new MilitaryRank(MilitaryGradeType.E8, "Kong Jun Er Ji Jun Shi Zhang"),
                    new MilitaryRank(MilitaryGradeType.E9, "Kong Jun Yi Ji Jun Shi Zhang"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Denmark, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O10, "General"),
                    new MilitaryRank(MilitaryGradeType.O9, "Generalløjtnant"),
                    new MilitaryRank(MilitaryGradeType.O8, "Generalmajor"),
                    new MilitaryRank(MilitaryGradeType.O7, "Brigadegeneral"),
                    new MilitaryRank(MilitaryGradeType.O6, "Oberst"),
                    new MilitaryRank(MilitaryGradeType.O5, "Oberstløjtnant"),
                    new MilitaryRank(MilitaryGradeType.O4, "Major"),
                    new MilitaryRank(MilitaryGradeType.O3, "Kaptajn"),
                    new MilitaryRank(MilitaryGradeType.O2, "Premierløjtnant"),
                    new MilitaryRank(MilitaryGradeType.O1, "Løjtnant"),
                    new MilitaryRank(MilitaryGradeType.E9, "Hærchefsergenten"),
                    new MilitaryRank(MilitaryGradeType.E9, "Chefsergent"),
                    new MilitaryRank(MilitaryGradeType.E8, "Seniorsergent"),
                    new MilitaryRank(MilitaryGradeType.E7, "Oversergent"),
                    new MilitaryRank(MilitaryGradeType.E5, "Sergent"),
                    new MilitaryRank(MilitaryGradeType.E4, "Officerselev Sergent"),
                    new MilitaryRank(MilitaryGradeType.E3, "Korporal"),
                    new MilitaryRank(MilitaryGradeType.E2, "Overkonstabel af 1. grad"),
                    new MilitaryRank(MilitaryGradeType.E1, "Overkonstabel"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Denmark, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O9, "Admiral"),
                    new MilitaryRank(MilitaryGradeType.O8, "Viceadmiral"),
                    new MilitaryRank(MilitaryGradeType.O7, "Kontreadmiral"),
                    new MilitaryRank(MilitaryGradeType.O6, "Flotilleadmiral"),
                    new MilitaryRank(MilitaryGradeType.O5, "Kommandør"),
                    new MilitaryRank(MilitaryGradeType.O4, "Kommandørkaptajn"),
                    new MilitaryRank(MilitaryGradeType.O3, "Orlogskaptajn"),
                    new MilitaryRank(MilitaryGradeType.O2, "Kaptajnløjtnant"),
                    new MilitaryRank(MilitaryGradeType.O1, "Premierløjtnant"),
                    new MilitaryRank(MilitaryGradeType.O1, "Løjtnant"),
                    new MilitaryRank(MilitaryGradeType.E9, "Søværnschefsergent"),
                    new MilitaryRank(MilitaryGradeType.E9, "Chefsergent"),
                    new MilitaryRank(MilitaryGradeType.E8, "Seniorsergent"),
                    new MilitaryRank(MilitaryGradeType.E7, "Oversergent"),
                    new MilitaryRank(MilitaryGradeType.E5, "Sergent"),
                    new MilitaryRank(MilitaryGradeType.E5, "Værnepligtig Sergent"),
                    new MilitaryRank(MilitaryGradeType.E4, "Korporal"),
                    new MilitaryRank(MilitaryGradeType.E3, "Marinespecialist"),
                    new MilitaryRank(MilitaryGradeType.E2, "Marineoverkonstabel"),
                    new MilitaryRank(MilitaryGradeType.E1, "Marinekonstabel"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Finland, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O9, "Kenraali"),
                    new MilitaryRank(MilitaryGradeType.O8, "Kenraaliluutnantti"),
                    new MilitaryRank(MilitaryGradeType.O7, "Kenraalimajuri"),
                    new MilitaryRank(MilitaryGradeType.O6, "Prikaatikenraali"),
                    new MilitaryRank(MilitaryGradeType.O5, "Eversti"),
                    new MilitaryRank(MilitaryGradeType.O4, "Everstiluutnantti"),
                    new MilitaryRank(MilitaryGradeType.O3, "Majuri"),
                    new MilitaryRank(MilitaryGradeType.O2, "Kapteeni"),
                    new MilitaryRank(MilitaryGradeType.O1, "Yliluutnantti"),
                    new MilitaryRank(MilitaryGradeType.O1, "Luutnantti"),
                    new MilitaryRank(MilitaryGradeType.O1, "Vänrikki"),
                    new MilitaryRank(MilitaryGradeType.E9, "Sotilasmestari"),
                    new MilitaryRank(MilitaryGradeType.E8, "Ylivääpeli"),
                    new MilitaryRank(MilitaryGradeType.E7, "Vääpeli"),
                    new MilitaryRank(MilitaryGradeType.E6, "Ylikersantti"),
                    new MilitaryRank(MilitaryGradeType.E5, "Kersantti"),
                    new MilitaryRank(MilitaryGradeType.E4, "Alikersantti"),
                    new MilitaryRank(MilitaryGradeType.E2, "Korpraali"),
                    new MilitaryRank(MilitaryGradeType.E1, "Sotamies"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Finland, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O9, "Amiraali"),
                    new MilitaryRank(MilitaryGradeType.O8, "Vara-amiraali"),
                    new MilitaryRank(MilitaryGradeType.O7, "Kontra-amiraali"),
                    new MilitaryRank(MilitaryGradeType.O6, "Lippueamiraali"),
                    new MilitaryRank(MilitaryGradeType.O5, "Kommodori"),
                    new MilitaryRank(MilitaryGradeType.O4, "Komentaja"),
                    new MilitaryRank(MilitaryGradeType.O3, "Komentajakapteeni"),
                    new MilitaryRank(MilitaryGradeType.O2, "Kapteeniluutnantti"),
                    new MilitaryRank(MilitaryGradeType.O1, "Yliluutnantti"),
                    new MilitaryRank(MilitaryGradeType.O1, "Luutnantti"),
                    new MilitaryRank(MilitaryGradeType.O1, "Aliluutnantti"),
                    new MilitaryRank(MilitaryGradeType.E9, "Sotilasmestari Militärmästare"),
                    new MilitaryRank(MilitaryGradeType.E8, "Ylipursimies Överbåtsman"),
                    new MilitaryRank(MilitaryGradeType.E7, "Pursimies Båtsman"),
                    new MilitaryRank(MilitaryGradeType.E6, "Ylikersantti Översergeant"),
                    new MilitaryRank(MilitaryGradeType.E5, "Kersantti Sergeant"),
                    new MilitaryRank(MilitaryGradeType.E4, "Alikersantti Undersergeant"),
                    new MilitaryRank(MilitaryGradeType.E2, "Ylimatruusi Övermatros"),
                    new MilitaryRank(MilitaryGradeType.E1, "Matruusi Matros"),
                }),
                new MilitaryBranch(MilitaryCategoryType.France, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O9, "Général d'armée"),
                    new MilitaryRank(MilitaryGradeType.O8, "Général de corps d'armée"),
                    new MilitaryRank(MilitaryGradeType.O7, "Général de division"),
                    new MilitaryRank(MilitaryGradeType.O6, "Général de brigade"),
                    new MilitaryRank(MilitaryGradeType.O5, "Colonel"),
                    new MilitaryRank(MilitaryGradeType.O4, "Lieutenant-Colonel"),
                    new MilitaryRank(MilitaryGradeType.O3, "Commandant"),
                    new MilitaryRank(MilitaryGradeType.O2, "Capitaine"),
                    new MilitaryRank(MilitaryGradeType.O1, "Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.O1, "Sous-Lieutenant"),
                    new MilitaryRank(MilitaryGradeType.E9, "Major"),
                    new MilitaryRank(MilitaryGradeType.E9, "Adjudant-chef"),
                    new MilitaryRank(MilitaryGradeType.E8, "Adjudant"),
                    new MilitaryRank(MilitaryGradeType.E6, "Sergent-chef"),
                    new MilitaryRank(MilitaryGradeType.E5, "Sergent"),
                    new MilitaryRank(MilitaryGradeType.E4, "Caporal-chef de première classe"),
                    new MilitaryRank(MilitaryGradeType.E4, "Caporal-chef"),
                    new MilitaryRank(MilitaryGradeType.E3, "Caporal"),
                    new MilitaryRank(MilitaryGradeType.E2, "Soldat de première classe"),
                    new MilitaryRank(MilitaryGradeType.E1, "Soldat"),
                }),
                new MilitaryBranch(MilitaryCategoryType.German, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.E1, "Flieger"),
                    new MilitaryRank(MilitaryGradeType.E2, "Gefreiter"),
                    new MilitaryRank(MilitaryGradeType.E3, "Obergefreiter"),
                    new MilitaryRank(MilitaryGradeType.E3, "Hauptgefreiter"),
                    new MilitaryRank(MilitaryGradeType.E4, "Stabsgefreiter"),
                    new MilitaryRank(MilitaryGradeType.E4, "Oberstabsgefreiter"),
                    new MilitaryRank(MilitaryGradeType.E5, "Unteroffizier"),
                    new MilitaryRank(MilitaryGradeType.E5, "Stabsunteroffizier"),
                    new MilitaryRank(MilitaryGradeType.E6, "Feldwebel"),
                    new MilitaryRank(MilitaryGradeType.E6, "Oberfeldwebel"),
                    new MilitaryRank(MilitaryGradeType.E7, "Hauptfeldwebel"),
                    new MilitaryRank(MilitaryGradeType.E8, "Stabsfeldwebel"),
                    new MilitaryRank(MilitaryGradeType.E9, "Oberstabsfeldwebel"),
                    new MilitaryRank(MilitaryGradeType.O1, "Leutnant"),
                    new MilitaryRank(MilitaryGradeType.O1, "Oberleutnant"),
                    new MilitaryRank(MilitaryGradeType.O2, "Hauptmann"),
                    new MilitaryRank(MilitaryGradeType.O2, "Stabshauptmann"),
                    new MilitaryRank(MilitaryGradeType.O3, "Major"),
                    new MilitaryRank(MilitaryGradeType.O4, "Oberstleutnant"),
                    new MilitaryRank(MilitaryGradeType.O5, "Oberst"),
                    new MilitaryRank(MilitaryGradeType.O6, "Brigadegeneral"),
                    new MilitaryRank(MilitaryGradeType.O7, "Generalmajor"),
                    new MilitaryRank(MilitaryGradeType.O8, "Generalleutnant"),
                    new MilitaryRank(MilitaryGradeType.O9, "General"),
                }),
                new MilitaryBranch(MilitaryCategoryType.German, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.E1, "Matrose"),
                    new MilitaryRank(MilitaryGradeType.E2, "Gefreiter"),
                    new MilitaryRank(MilitaryGradeType.E3, "Obergefreiter"),
                    new MilitaryRank(MilitaryGradeType.E3, "Hauptgefreiter"),
                    new MilitaryRank(MilitaryGradeType.E4, "Stabsgefreiter"),
                    new MilitaryRank(MilitaryGradeType.E4, "Oberstabsgefreiter"),
                    new MilitaryRank(MilitaryGradeType.E5, "Maat"),
                    new MilitaryRank(MilitaryGradeType.E5, "Obermaat"),
                    new MilitaryRank(MilitaryGradeType.E6, "Bootsmann"),
                    new MilitaryRank(MilitaryGradeType.E6, "Oberbootsmann"),
                    new MilitaryRank(MilitaryGradeType.E7, "Hauptbootsmann"),
                    new MilitaryRank(MilitaryGradeType.E8, "Stabsbootsmann"),
                    new MilitaryRank(MilitaryGradeType.E9, "Oberstabsbootsmann"),
                    new MilitaryRank(MilitaryGradeType.O1, "Leutnant zur See"),
                    new MilitaryRank(MilitaryGradeType.O1, "Oberleutnant zur See"),
                    new MilitaryRank(MilitaryGradeType.O2, "Kapitänleutnant"),
                    new MilitaryRank(MilitaryGradeType.O2, "Stabskapitänleutnant"),
                    new MilitaryRank(MilitaryGradeType.O3, "Korvettenkapitän"),
                    new MilitaryRank(MilitaryGradeType.O4, "Fregattenkapitän"),
                    new MilitaryRank(MilitaryGradeType.O5, "Kapitän zur See"),
                    new MilitaryRank(MilitaryGradeType.O6, "Flottillenadmiral"),
                    new MilitaryRank(MilitaryGradeType.O7, "Konteradmiral"),
                    new MilitaryRank(MilitaryGradeType.O8, "Vizeadmiral"),
                    new MilitaryRank(MilitaryGradeType.O9, "Admiral"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Poland, MilitaryBranchType.Army, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.E9, "Starszy chorazy sztabowy"),
                    new MilitaryRank(MilitaryGradeType.E9, "Starszy chorazy"),
                    new MilitaryRank(MilitaryGradeType.E8, "Chorazy"),
                    new MilitaryRank(MilitaryGradeType.E7, "Mlodszy chorazy"),
                    new MilitaryRank(MilitaryGradeType.E6, "Starszy sierzant"),
                    new MilitaryRank(MilitaryGradeType.E5, "Sierzant"),
                    new MilitaryRank(MilitaryGradeType.E4, "Plutonowy"),
                    new MilitaryRank(MilitaryGradeType.E4, "Starszy kapral"),
                    new MilitaryRank(MilitaryGradeType.E3, "Kapral"),
                    new MilitaryRank(MilitaryGradeType.E2, "Starszy szeregowy"),
                    new MilitaryRank(MilitaryGradeType.E1, "Szeregowy"),
                    new MilitaryRank(MilitaryGradeType.O9, "General"),
                    new MilitaryRank(MilitaryGradeType.O8, "General broni"),
                    new MilitaryRank(MilitaryGradeType.O7, "General dywizji"),
                    new MilitaryRank(MilitaryGradeType.O6, "General brygady"),
                    new MilitaryRank(MilitaryGradeType.O5, "Pulkownik"),
                    new MilitaryRank(MilitaryGradeType.O4, "Podpulkownik"),
                    new MilitaryRank(MilitaryGradeType.O3, "Major"),
                    new MilitaryRank(MilitaryGradeType.O2, "Kapitan"),
                    new MilitaryRank(MilitaryGradeType.O1, "Porucznik"),
                    new MilitaryRank(MilitaryGradeType.O1, "Podporucznik"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Poland, MilitaryBranchType.Navy, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.O9, "Admiral"),
                    new MilitaryRank(MilitaryGradeType.O8, "Admiral floty"),
                    new MilitaryRank(MilitaryGradeType.O7, "Wiceadmiral"),
                    new MilitaryRank(MilitaryGradeType.O6, "Kontradmiral"),
                    new MilitaryRank(MilitaryGradeType.O5, "Komandor"),
                    new MilitaryRank(MilitaryGradeType.O4, "Komandor porucznik"),
                    new MilitaryRank(MilitaryGradeType.O3, "Komandor podporucznik"),
                    new MilitaryRank(MilitaryGradeType.O2, "Kapitan marynarki"),
                    new MilitaryRank(MilitaryGradeType.O1, "Porucznik marynarki"),
                    new MilitaryRank(MilitaryGradeType.O1, "Podporucznik marynarki"),
                    new MilitaryRank(MilitaryGradeType.E9, "Starszy chorazy sztabowy marynarki"),
                    new MilitaryRank(MilitaryGradeType.E9, "Starszy chorazy marynarki"),
                    new MilitaryRank(MilitaryGradeType.E8, "Chorazy marynarki"),
                    new MilitaryRank(MilitaryGradeType.E7, "Mlodszy chorazy marynarki"),
                    new MilitaryRank(MilitaryGradeType.E6, "Starszy bosman"),
                    new MilitaryRank(MilitaryGradeType.E5, "Bosman"),
                    new MilitaryRank(MilitaryGradeType.E4, "Bosmanmat"),
                    new MilitaryRank(MilitaryGradeType.E4, "Starszy mat"),
                    new MilitaryRank(MilitaryGradeType.E3, "Mat"),
                    new MilitaryRank(MilitaryGradeType.E2, "Starszy marynarz"),
                    new MilitaryRank(MilitaryGradeType.E1, "Marynarz"),
                }),
                new MilitaryBranch(MilitaryCategoryType.Unique, MilitaryBranchType.Unique, new List<MilitaryRank>()
                {
                    new MilitaryRank(MilitaryGradeType.U, "Warlord"),
                    new MilitaryRank(MilitaryGradeType.U, "Dragoon"),
                    new MilitaryRank(MilitaryGradeType.U, "Trooper"),
                    new MilitaryRank(MilitaryGradeType.U, "Shock Trooper"),
                    new MilitaryRank(MilitaryGradeType.U, "Shieldmaiden"),
                    new MilitaryRank(MilitaryGradeType.U, "Gladiator"),
                    new MilitaryRank(MilitaryGradeType.U, "Beserker"),
                    new MilitaryRank(MilitaryGradeType.U, "Crusader"),
                    new MilitaryRank(MilitaryGradeType.U, "Dog Solider"),
                    new MilitaryRank(MilitaryGradeType.U, "Eagle Warrior"),
                    new MilitaryRank(MilitaryGradeType.U, "Highlander"),
                    new MilitaryRank(MilitaryGradeType.U, "Housecarl"),
                    new MilitaryRank(MilitaryGradeType.U, "Immortal"),
                    new MilitaryRank(MilitaryGradeType.U, "Jaguar Warrior"),
                    new MilitaryRank(MilitaryGradeType.U, "Knight"),
                    new MilitaryRank(MilitaryGradeType.U, "Ninja"),
                    new MilitaryRank(MilitaryGradeType.U, "Templar"),
                    new MilitaryRank(MilitaryGradeType.U, "Samuari"),
                    new MilitaryRank(MilitaryGradeType.U, "Commando"),
                    new MilitaryRank(MilitaryGradeType.U, "Ranger"),
                    new MilitaryRank(MilitaryGradeType.U, "Sniper"),
                    new MilitaryRank(MilitaryGradeType.U, "Engineer"),
                    new MilitaryRank(MilitaryGradeType.U, "Sapper"),
                    new MilitaryRank(MilitaryGradeType.U, "Grenadier"),
                }),
            };
        }
    }
}
