namespace DMData.Names
{
    public enum NameGenderType
    {
        Female,
        Male,
        Unisex,
    }

    public enum MilitaryBranchType
    {
        Branch,
        Airforce,
        Army,
        Cavalry,
        Marines,
        Navy,
        Unique,
    }
    public enum MilitaryCategoryType
    {
        China,
        Denmark,
        Finland,
        France,
        German,
        Greek,
        Poland,
        Roman,
        Unique,
        UnitedStates,
    }
    public enum MilitaryGradeType
    {
        E1,
        E2,
        E3,
        E4,
        E5,
        E6,
        E7,
        E8,
        E9,
        O1,
        O10,
        O2,
        O3,
        O4,
        O5,
        O6,
        O7,
        O8,
        O9,
        U,
        W1,
        W2,
        W3,
        W4,
        W5,
    }

    public enum NameCategoryType
    {
        Arabic,
        Chinese,
        Czech,
        Danish,
        Dragonborn,
        Dutch,
        Dwarf,
        Egyptian,
        Elf,
        English,
        Finnish,
        French,
        German,
        Gnome,
        Greek,
        Halfling,
        HalfOrc,
        Icelandic,
        Indian,
        Irish,
        Italian,
        Japanese,
        Korean,
        Mesoamerican,
        NigerCongo,
        Polynesian,
        Portuguese,
        Roman,
        Scottish,
        Slavic,
        Spanish,
        Swedish,
        Tiefling,
        Turkish,
        Welsh,
    }

    public enum NobilityCategoryType
    {
        Czech,
        Danish,
        Dutch,
        European,
        Finnish,
        French,
        German,
        Hungarian,
        Icelandic,
        Italitan,
        Latvian,
        Lithuanian,
        Norwegian,
        Polish,
        Portuguese,
        Roman,
        Romanian,
        Serbian,
        Slovak,
        Slovene,
        Spanish,
        Swedish,
        Welsh,
    }

    public enum TitleCategoryType
    {
        Academics,
        Clan,
        Government,
        Institutional,
        Medical,
        Military,
        Religious,
        Social,
        Tribe,
    }
}