namespace DMData.Names
{
    public enum NobilityCategoryType
    {
        Czech,
        Danish,
        Dutch,
        European,
        Finnish,
        French,
        German,
        Hungarian,
        Icelandic,
        Italitan,
        Latvian,
        Lithuanian,
        Norwegian,
        Polish,
        Portuguese,
        Roman,
        Romanian,
        Serbian,
        Slovak,
        Slovene,
        Spanish,
        Swedish,
        Welsh,
    }
}