namespace DMData.Stats
{
    public enum AbilityCategoryType
    {
        Strength,
        Dexterity,
        Constitution,
        Intelligence,
        Wisdom,
        Charisma
    }
    public enum MovementCategoryType
    {
        Walk,
        Burrow,
        Fly,
        Swim,
        Climb,
    }
    public enum LevelType
    {
        L0,
        LEigth,
        LQuarter,
        LHalf,
        L1,
        L2,
        L3,
        L4,
        L5,
        L6,
        L7,
        L8,
        L9,
        L10,
        L11,
        L12,
        L13,
        L14,
        L15,
        L16,
        L17,
        L18,
        L19,
        L20,
        L21,
        L22,
        L23,
        L24,
        L25,
        L26,
        L27,
        L28,
        L29,
        L30
    }
    public enum TerrainType
    {
        Normal,
        Difficult,
    }
    public enum SizeCategoryType
    {
        Tiny,
        Small,
        Medium,
        Large,
        Huge,
        Gargantuan,
    }
    public enum AlignmentType
    {
        LawfulGood,
        LawfulEvil,
        LawfulNeutral,
        NeutralGood,
        Neutral,
        NeutralEvil,
        ChaoticGood,
        ChaoticNeutral,
        ChaoticEvil,
        Unaligned,
    }
    public enum LanguageType
    {
        Common,
        Dwarvish,
        Elvish,
        Giant,
        Gnomish,
        Goblin,
        Halfling,
        Orc,
        Abyssal,
        Celestial,
        DeepSpeech,
        Infernal,
        Primordial,
        Sylvan,
        Undercommon
    }
    public enum LangauageCategoryType
    {
        Standard,
        ShatteredWorlds,
    }
    public enum SenseType
    {
        Blindsight,
        Darkvision,
        Termorsense,
        Truesight,
    }
}
